package trending

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/alexcollie/kaizen/pkg/storage"
)

// RenderHTMLChart generates an interactive HTML chart using Chart.js
func RenderHTMLChart(metricName string, points []storage.TimeSeriesPoint, scopePath string) (string, error) {
	if len(points) == 0 {
		return "", fmt.Errorf("no data available for metric: %s", metricName)
	}

	// Prepare data for JSON
	labels := make([]string, len(points))
	data := make([]float64, len(points))

	for i, p := range points {
		labels[i] = p.Timestamp.Format("2006-01-02 15:04")
		data[i] = p.Value
	}

	// Create JSON data
	chartData := map[string]interface{}{
		"labels": labels,
		"data":   data,
	}

	jsonData, err := json.Marshal(chartData)
	if err != nil {
		return "", err
	}

	// Create title
	title := metricName
	if scopePath != "" {
		title = fmt.Sprintf("%s - %s", metricName, scopePath)
	}

	html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kaizen Trend: %s</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #F5F1E8;
            min-height: 100vh;
            padding: 40px 20px;
        }
        .container {
            max-width: 1000px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 4px 12px rgba(45, 45, 42, 0.12);
            padding: 40px;
        }
        h1 {
            color: #C97064;
            margin-bottom: 10px;
            font-size: 28px;
            font-weight: 700;
        }
        .subtitle {
            color: #6B6B68;
            margin-bottom: 30px;
            font-size: 14px;
        }
        .chart-container {
            position: relative;
            height: 400px;
            margin-bottom: 30px;
            background: #F5F1E8;
            border-radius: 12px;
            padding: 20px;
        }
        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-top: 30px;
        }
        .stat-card {
            background: #EBE6DD;
            padding: 20px;
            border-radius: 12px;
            border-left: 4px solid #C97064;
            transition: all 0.2s ease;
        }
        .stat-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 2px 8px rgba(201, 112, 100, 0.15);
        }
        .stat-label {
            color: #6B6B68;
            font-size: 12px;
            text-transform: uppercase;
            margin-bottom: 8px;
            font-weight: 600;
            letter-spacing: 0.05em;
        }
        .stat-value {
            color: #2D2D2A;
            font-size: 24px;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #E8E4DA;
            color: #9A9A97;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📈 %s</h1>
        <div class="subtitle">Generated at %s</div>

        <div class="chart-container">
            <canvas id="trendChart"></canvas>
        </div>

        <div class="stats">
            <div class="stat-card">
                <div class="stat-label">Current Value</div>
                <div class="stat-value" id="currentValue">-</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Min Value</div>
                <div class="stat-value" id="minValue">-</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Max Value</div>
                <div class="stat-value" id="maxValue">-</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Average</div>
                <div class="stat-value" id="avgValue">-</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Change</div>
                <div class="stat-value" id="changeValue">-</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Data Points</div>
                <div class="stat-value">%d</div>
            </div>
        </div>

        <div class="footer">
            Generated by Kaizen · %s
        </div>
    </div>

    <script>
        const chartData = %s;

        const ctx = document.getElementById('trendChart').getContext('2d');
        const chart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: chartData.labels,
                datasets: [{
                    label: '%s',
                    data: chartData.data,
                    borderColor: '#C97064',
                    backgroundColor: 'rgba(201, 112, 100, 0.1)',
                    borderWidth: 3,
                    fill: true,
                    tension: 0.4,
                    pointRadius: 5,
                    pointBackgroundColor: '#C97064',
                    pointBorderColor: '#fff',
                    pointBorderWidth: 2,
                    pointHoverRadius: 7,
                    pointHoverBackgroundColor: '#B85C50',
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    },
                    tooltip: {
                        backgroundColor: 'rgba(0, 0, 0, 0.8)',
                        padding: 12,
                        titleFont: { size: 14 },
                        bodyFont: { size: 13 },
                        cornerRadius: 6,
                    }
                },
                scales: {
                    y: {
                        beginAtZero: false,
                        grid: {
                            color: '#f0f0f0',
                        },
                        ticks: {
                            color: '#666',
                        }
                    },
                    x: {
                        grid: {
                            display: false,
                        },
                        ticks: {
                            color: '#666',
                            maxRotation: 45,
                            minRotation: 0,
                        }
                    }
                }
            }
        });

        // Calculate and display statistics
        const values = chartData.data;
        const min = Math.min(...values);
        const max = Math.max(...values);
        const avg = values.reduce((a, b) => a + b) / values.length;
        const current = values[values.length - 1];
        const change = current - values[0];

        document.getElementById('currentValue').textContent = current.toFixed(1);
        document.getElementById('minValue').textContent = min.toFixed(1);
        document.getElementById('maxValue').textContent = max.toFixed(1);
        document.getElementById('avgValue').textContent = avg.toFixed(1);
        document.getElementById('changeValue').textContent = (change >= 0 ? '+' : '') + change.toFixed(1);
    </script>
</body>
</html>
`, title, title, time.Now().Format("2006-01-02 15:04:05"), len(points), time.Now().Format("2006-01-02 15:04:05"), string(jsonData), metricName)

	return html, nil
}

// WriteHTMLToFile writes HTML chart to file and returns path
func WriteHTMLToFile(html, outputPath string) error {
	return os.WriteFile(outputPath, []byte(html), 0644)
}

// FormatChartFilename generates a filename for the chart
func FormatChartFilename(metricName string) string {
	return fmt.Sprintf("kaizen-trend-%s.html", metricName)
}
